# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_geoinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityarea',
            name='name_bd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cityarea',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_bd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='name_bd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='name_bd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='upazila',
            name='name_bd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='upazila',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
